Fix compile warnings due to invalid pointer arithmetic.
./iptables/include/linux/netfilter_ipv6/ip6_tables.h: In function ‘xt_entry_target* ip6t_get_target(ip6t_entry*)’:
./iptables/include/linux/netfilter_ipv6/ip6_tables.h:258:24: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
./iptables/include/linux/netfilter_ipv6/ip6_tables.h:258:24: error: invalid conversion from ‘void*’ to ‘xt_entry_target*’ [-fpermissive]

IPT_MATCH_ITERATE(fw, add_match, &fw->ip, builder);
...
netgraph-server.cc:285:177: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
netgraph-server.cc:285:177: error: invalid conversion from ‘void*’ to ‘xt_entry_match*’ [-fpermissive]